---
apiVersion: v1
kind: Service
metadata:
  name: announcement
  labels:
    app: announcement
spec:
  type: ClusterIP
  selector:
    app: announcement
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80